//DO NOT EDIT MANUALLY, let automation work hard.

// auto-generated by PinoutLogic.java based on config/boards/zxbr/connectors/main.yaml
#include "pch.h"

// see comments at declaration in pin_repository.h
const char * getBoardSpecificPinName(brain_pin_e brainPin) {
	switch(brainPin) {
		case Gpio::A2: return "TPS Reference Input (A2)";
		case Gpio::B14: return "Relay (B14)";
		case Gpio::B15: return "Relay (B15)";
		case Gpio::B5: return "Crank Input (B5)";
		case Gpio::C6: return "CrankShaft Input (C6)";
		case Gpio::D12: return "Ignition 1 Output (D12)";
		case Gpio::D13: return "Ignition 2 Output (D13)";
		case Gpio::D8: return "Fuel Pump Relay (D8)";
		case Gpio::E13: return "Injector 2 Output (E13)";
		case Gpio::E14: return "Injector 1 Output (E14)";
		case Gpio::E5: return "Tachometer (E5)";
		default: return nullptr;
	}
	return nullptr;
}
