pins:
    - id: B15
      class: outputs
      ts_name: Relay (B15)
    - id: B14
      class: outputs
      ts_name: Relay (B14)
    - id: D8
      class: outputs
      ts_name: Fuel Pump Relay (D8)
    - id: E5
      class: outputs
      ts_name: Tachometer (E5)
    - id: [B5, B5]
      class: [switch_inputs, event_inputs]
      ts_name: Crank Input (B5)
    - id: [C6, C6]
      class: [switch_inputs, event_inputs]
      ts_name: CrankShaft Input (C6)
    - id: EFI_ADC_1
      class: analog_inputs
      ts_name: Battery Reference Input (A1)
    - id: [A2, EFI_ADC_2]
      class: [switch_inputs, analog_inputs]
      ts_name: TPS Reference Input (A2)
    - id: EFI_ADC_15
      class: analog_inputs
      ts_name: CLT Reference Input (C5)
    - id: EFI_ADC_8
      class: analog_inputs
      ts_name: IAT Reference Input (B0)
    - id: EFI_ADC_9
      class: analog_inputs
      ts_name: O2 Reference Input (B1)
    - id: EFI_ADC_14
      class: analog_inputs
      ts_name: MAP Pressure Reference Input(C4)
    - id: E13
      class: outputs
      ts_name: Injector 2 Output (E13)
    - id: E14
      class: outputs
      ts_name: Injector 1 Output (E14)
    - id: D13
      class: outputs
      ts_name: Ignition 2 Output (D13)
    - id: D12
      class: outputs
      ts_name: Ignition 1 Output (D12)
