name: Simulator

on: [push, pull_request]

jobs:
  # This is just to ensure the simulator compiles on Linux
  build-simulator:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive
    - uses: actions/setup-java@v3
      with:
        distribution: 'zulu'
        java-version: '8'

    - name: Install multilib
      run: |
        sudo apt-get update
        sudo apt-get install gcc-multilib g++-multilib mtools dosfstools zip

    - name: Generate Configs for simulator
      working-directory: ./firmware/
      run: ./gen_config_default.sh

    - name: Generate Enums
      working-directory: ./firmware/
      run: ./gen_enum_to_string.sh

    - name: Generate Live Documentation
      working-directory: ./firmware/
      run: ./gen_live_documentation.sh

    - name: Compile Simulator
      working-directory: ./simulator/
      run: ./compile.sh

    - name: Run Simulator (10 seconds)
      working-directory: ./simulator/
      run: ./build/rusefi_simulator 10

    - name: Upload built simulator
      uses: actions/upload-artifact@v3
      with:
        name: rusefi_simulator_linux
        path: ./simulator/build/rusefi_simulator
